# Generated by Django 5.2.15 on 2026-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band_name", models.CharField(max_length=200)),
                ("venue", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "ticket_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
            ],
        ),
    ]
