# Generated by Django 5.2.15 on 2026-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("album", models.CharField(blank=True, max_length=200)),
                ("year", models.IntegerField(default=0)),
                ("lyrics", models.TextField(blank=True)),
            ],
        ),
    ]
